### ISSUE TITLE
conferer-warp fails to build with warp >= 3.3.22

### ISSUE THREAD

**Issue by stuebinm** [ludat/conferer#105]
`conferer-warp` fails to build:

~~~
Building library for conferer-warp-1.1.0.0..
[1 of 2] Compiling Conferer.FromConfig.Warp ( src/Conferer/FromConfig/Warp.hs, dist/build/Conferer/FromConfig/Warp.o, dist/build/Conferer/FromConfig/Wa
rp.dyn_o )

src/Conferer/FromConfig/Warp.hs:161:12: error:
    • Constructor ‘Settings’ does not have the required strict field(s): settingsAccept,
                                                                         settingsMaxBuilderResponseBufferSize
    • In the first argument of ‘return’, namely ‘Settings {..}’
      In a stmt of a 'do' block: return Settings {..}
      In the expression:
        do config <- addDefaultsAfterDeconstructingToDefaults
                       deconstructSettingsToDefaults key originalConfig
           settingsPort <- fetchFromConfig (key /. "port") config
           settingsHost <- fetchFromConfig (key /. "host") config
           settingsOnException <- fetchFromConfig
                                    (key /. "onException") config
           ....
    |
161 |     return Settings{..}
    |            ^^^^^^^^^^^^
~~~

looks like `warp` has since added two [new fields](https://hackage.haskell.org/package/warp-3.3.23/docs/Network-Wai-Handler-Warp-Internal.html#v:settingsMaxBuilderResponseBufferSize) to the `Settings` type.

After setting a maximum warp version < 3.3.22 it builds fine.

**Comment by ludat** [comment]
Hi @stuebinm,

Thanks for the report.

I've release `conferer-warp` 1.1.0.1 which supports newer warp, let me know if the issue is actually fix and then I'll close the issue

**Comment by stuebinm** [comment]
Yup, that fixed it, builds fine now. Thanks!
