### ISSUE TITLE
conferer-aeson fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [ludat/conferer#89]
```
conferer-aeson                 > Building library for conferer-aeson-1.1.0.1..
conferer-aeson                 > [1 of 3] Compiling Conferer.FromConfig.Aeson
conferer-aeson                 > [2 of 3] Compiling Conferer.Source.Aeson
conferer-aeson                 > 
conferer-aeson                 > /tmp/stack-2f044d9799429c9c/conferer-aeson-1.1.0.1/src/Conferer/Source/Aeson.hs:46:15: error:
conferer-aeson                 >     Ambiguous occurrence ‘Key’
conferer-aeson                 >     It could refer to
conferer-aeson                 >        either ‘Data.Aeson.Key’,
conferer-aeson                 >               imported from ‘Data.Aeson’ at src/Conferer/Source/Aeson.hs:12:1-17
conferer-aeson                 >               (and originally defined in ‘Data.Aeson.Key’)
conferer-aeson                 >            or ‘Conferer.Source.Key’,
conferer-aeson                 >               imported from ‘Conferer.Source’ at src/Conferer/Source/Aeson.hs:30:1-22
conferer-aeson                 >               (and originally defined in ‘Conferer.Key.Internal’)
conferer-aeson                 >    |
conferer-aeson                 > 46 | fromConfig :: Key -> SourceCreator
conferer-aeson                 >    |               ^^^
conferer-aeson                 > 
conferer-aeson                 > /tmp/stack-2f044d9799429c9c/conferer-aeson-1.1.0.1/src/Conferer/Source/Aeson.hs:107:17: error:
conferer-aeson                 >     Ambiguous occurrence ‘Key’
conferer-aeson                 >     It could refer to
conferer-aeson                 >        either ‘Data.Aeson.Key’,
conferer-aeson                 >               imported from ‘Data.Aeson’ at src/Conferer/Source/Aeson.hs:12:1-17
conferer-aeson                 >               (and originally defined in ‘Data.Aeson.Key’)
conferer-aeson                 >            or ‘Conferer.Source.Key’,
conferer-aeson                 >               imported from ‘Conferer.Source’ at src/Conferer/Source/Aeson.hs:30:1-22
conferer-aeson                 >               (and originally defined in ‘Conferer.Key.Internal’)
conferer-aeson                 >     |
conferer-aeson                 > 107 | traverseJSON :: Key -> Value -> Maybe Value
conferer-aeson                 >     |                 ^^^
conferer-aeson                 > 
conferer-aeson                 > /tmp/stack-2f044d9799429c9c/conferer-aeson-1.1.0.1/src/Conferer/Source/Aeson.hs:137:29: error:
conferer-aeson                 >     Ambiguous occurrence ‘Key’
conferer-aeson                 >     It could refer to
conferer-aeson                 >        either ‘Data.Aeson.Key’,
conferer-aeson                 >               imported from ‘Data.Aeson’ at src/Conferer/Source/Aeson.hs:12:1-17
conferer-aeson                 >               (and originally defined in ‘Data.Aeson.Key’)
conferer-aeson                 >            or ‘Conferer.Source.Key’,
conferer-aeson                 >               imported from ‘Conferer.Source’ at src/Conferer/Source/Aeson.hs:30:1-22
conferer-aeson                 >               (and originally defined in ‘Conferer.Key.Internal’)
conferer-aeson                 >     |
conferer-aeson                 > 137 | listKeysInJSON :: Value -> [Key]
conferer-aeson                 >     |                             ^^^
conferer-aeson                 > 
conferer-aeson                 > /tmp/stack-2f044d9799429c9c/conferer-aeson-1.1.0.1/src/Conferer/Source/Aeson.hs:140:9: error:
conferer-aeson                 >     Ambiguous occurrence ‘Key’
conferer-aeson                 >     It could refer to
conferer-aeson                 >        either ‘Data.Aeson.Key’,
conferer-aeson                 >               imported from ‘Data.Aeson’ at src/Conferer/Source/Aeson.hs:12:1-17
conferer-aeson                 >               (and originally defined in ‘Data.Aeson.Key’)
conferer-aeson                 >            or ‘Conferer.Source.Key’,
conferer-aeson                 >               imported from ‘Conferer.Source’ at src/Conferer/Source/Aeson.hs:30:1-22
conferer-aeson                 >               (and originally defined in ‘Conferer.Key.Internal’)
conferer-aeson                 >     |
conferer-aeson                 > 140 |   go :: Key -> Value -> [Key]
conferer-aeson                 >     |         ^^^
conferer-aeson                 > 
conferer-aeson                 > /tmp/stack-2f044d9799429c9c/conferer-aeson-1.1.0.1/src/Conferer/Source/Aeson.hs:140:26: error:
conferer-aeson                 >     Ambiguous occurrence ‘Key’
conferer-aeson                 >     It could refer to
conferer-aeson                 >        either ‘Data.Aeson.Key’,
conferer-aeson                 >               imported from ‘Data.Aeson’ at src/Conferer/Source/Aeson.hs:12:1-17
conferer-aeson                 >               (and originally defined in ‘Data.Aeson.Key’)
conferer-aeson                 >            or ‘Conferer.Source.Key’,
conferer-aeson                 >               imported from ‘Conferer.Source’ at src/Conferer/Source/Aeson.hs:30:1-22
conferer-aeson                 >               (and originally defined in ‘Conferer.Key.Internal’)
conferer-aeson                 >     |
conferer-aeson                 > 140 |   go :: Key -> Value -> [Key]
conferer-aeson                 >     |                          ^^^
```

**Comment by ludat** [comment]
This has been fixed by conferer-aeson-1.2.0.2 which is already released on hackage mostly as a backport of #88
